/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAiToolsIndexRouteImport } from './routes/_authenticated/ai-tools/index'
import { Route as AuthenticatedAiToolsFattyLiverAssessmentRouteImport } from './routes/_authenticated/ai-tools/fatty-liver-assessment'
import { Route as AuthenticatedAiToolsLiverFibrosisRouteImport } from './routes/_authenticated/ai-tools/liver/fibrosis'
import { Route as AuthenticatedAiToolsLiverPredictRouteImport } from './routes/_authenticated/ai-tools/liver/predict'
import { Route as AuthenticatedAiToolsLiverSmcLudRouteImport } from './routes/_authenticated/ai-tools/liver/smc-lud'
import { Route as AuthenticatedAiToolsLiverSteatosisRouteImport } from './routes/_authenticated/ai-tools/liver/steatosis'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiToolsIndexRoute =
  AuthenticatedAiToolsIndexRouteImport.update({
    id: '/ai-tools/',
    path: '/ai-tools/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiToolsFattyLiverAssessmentRoute =
  AuthenticatedAiToolsFattyLiverAssessmentRouteImport.update({
    id: '/ai-tools/fatty-liver-assessment',
    path: '/ai-tools/fatty-liver-assessment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiToolsLiverFibrosisRoute =
  AuthenticatedAiToolsLiverFibrosisRouteImport.update({
    id: '/ai-tools/liver/fibrosis',
    path: '/ai-tools/liver/fibrosis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiToolsLiverPredictRoute =
  AuthenticatedAiToolsLiverPredictRouteImport.update({
    id: '/ai-tools/liver/predict',
    path: '/ai-tools/liver/predict',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiToolsLiverSmcLudRoute =
  AuthenticatedAiToolsLiverSmcLudRouteImport.update({
    id: '/ai-tools/liver/smc-lud',
    path: '/ai-tools/liver/smc-lud',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiToolsLiverSteatosisRoute =
  AuthenticatedAiToolsLiverSteatosisRouteImport.update({
    id: '/ai-tools/liver/steatosis',
    path: '/ai-tools/liver/steatosis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicRoute
  '/sign-in': typeof SignInRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ai-tools/fatty-liver-assessment': typeof AuthenticatedAiToolsFattyLiverAssessmentRoute
  '/ai-tools/': typeof AuthenticatedAiToolsIndexRoute
  '/ai-tools/liver/fibrosis': typeof AuthenticatedAiToolsLiverFibrosisRoute
  '/ai-tools/liver/predict': typeof AuthenticatedAiToolsLiverPredictRoute
  '/ai-tools/liver/smc-lud': typeof AuthenticatedAiToolsLiverSmcLudRoute
  '/ai-tools/liver/steatosis': typeof AuthenticatedAiToolsLiverSteatosisRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicRoute
  '/sign-in': typeof SignInRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ai-tools/fatty-liver-assessment': typeof AuthenticatedAiToolsFattyLiverAssessmentRoute
  '/ai-tools': typeof AuthenticatedAiToolsIndexRoute
  '/ai-tools/liver/fibrosis': typeof AuthenticatedAiToolsLiverFibrosisRoute
  '/ai-tools/liver/predict': typeof AuthenticatedAiToolsLiverPredictRoute
  '/ai-tools/liver/smc-lud': typeof AuthenticatedAiToolsLiverSmcLudRoute
  '/ai-tools/liver/steatosis': typeof AuthenticatedAiToolsLiverSteatosisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/ai-tools/fatty-liver-assessment': typeof AuthenticatedAiToolsFattyLiverAssessmentRoute
  '/_authenticated/ai-tools/': typeof AuthenticatedAiToolsIndexRoute
  '/_authenticated/ai-tools/liver/fibrosis': typeof AuthenticatedAiToolsLiverFibrosisRoute
  '/_authenticated/ai-tools/liver/predict': typeof AuthenticatedAiToolsLiverPredictRoute
  '/_authenticated/ai-tools/liver/smc-lud': typeof AuthenticatedAiToolsLiverSmcLudRoute
  '/_authenticated/ai-tools/liver/steatosis': typeof AuthenticatedAiToolsLiverSteatosisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/appointments'
    | '/dashboard'
    | '/patients'
    | '/profile'
    | '/ai-tools/fatty-liver-assessment'
    | '/ai-tools/'
    | '/ai-tools/liver/fibrosis'
    | '/ai-tools/liver/predict'
    | '/ai-tools/liver/smc-lud'
    | '/ai-tools/liver/steatosis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/appointments'
    | '/dashboard'
    | '/patients'
    | '/profile'
    | '/ai-tools/fatty-liver-assessment'
    | '/ai-tools'
    | '/ai-tools/liver/fibrosis'
    | '/ai-tools/liver/predict'
    | '/ai-tools/liver/smc-lud'
    | '/ai-tools/liver/steatosis'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/sign-in'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/patients'
    | '/_authenticated/profile'
    | '/_authenticated/ai-tools/fatty-liver-assessment'
    | '/_authenticated/ai-tools/'
    | '/_authenticated/ai-tools/liver/fibrosis'
    | '/_authenticated/ai-tools/liver/predict'
    | '/_authenticated/ai-tools/liver/smc-lud'
    | '/_authenticated/ai-tools/liver/steatosis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools/': {
      id: '/_authenticated/ai-tools/'
      path: '/ai-tools'
      fullPath: '/ai-tools/'
      preLoaderRoute: typeof AuthenticatedAiToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools/fatty-liver-assessment': {
      id: '/_authenticated/ai-tools/fatty-liver-assessment'
      path: '/ai-tools/fatty-liver-assessment'
      fullPath: '/ai-tools/fatty-liver-assessment'
      preLoaderRoute: typeof AuthenticatedAiToolsFattyLiverAssessmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools/liver/fibrosis': {
      id: '/_authenticated/ai-tools/liver/fibrosis'
      path: '/ai-tools/liver/fibrosis'
      fullPath: '/ai-tools/liver/fibrosis'
      preLoaderRoute: typeof AuthenticatedAiToolsLiverFibrosisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools/liver/predict': {
      id: '/_authenticated/ai-tools/liver/predict'
      path: '/ai-tools/liver/predict'
      fullPath: '/ai-tools/liver/predict'
      preLoaderRoute: typeof AuthenticatedAiToolsLiverPredictRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools/liver/smc-lud': {
      id: '/_authenticated/ai-tools/liver/smc-lud'
      path: '/ai-tools/liver/smc-lud'
      fullPath: '/ai-tools/liver/smc-lud'
      preLoaderRoute: typeof AuthenticatedAiToolsLiverSmcLudRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-tools/liver/steatosis': {
      id: '/_authenticated/ai-tools/liver/steatosis'
      path: '/ai-tools/liver/steatosis'
      fullPath: '/ai-tools/liver/steatosis'
      preLoaderRoute: typeof AuthenticatedAiToolsLiverSteatosisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAiToolsFattyLiverAssessmentRoute: typeof AuthenticatedAiToolsFattyLiverAssessmentRoute
  AuthenticatedAiToolsIndexRoute: typeof AuthenticatedAiToolsIndexRoute
  AuthenticatedAiToolsLiverFibrosisRoute: typeof AuthenticatedAiToolsLiverFibrosisRoute
  AuthenticatedAiToolsLiverPredictRoute: typeof AuthenticatedAiToolsLiverPredictRoute
  AuthenticatedAiToolsLiverSmcLudRoute: typeof AuthenticatedAiToolsLiverSmcLudRoute
  AuthenticatedAiToolsLiverSteatosisRoute: typeof AuthenticatedAiToolsLiverSteatosisRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAiToolsFattyLiverAssessmentRoute:
    AuthenticatedAiToolsFattyLiverAssessmentRoute,
  AuthenticatedAiToolsIndexRoute: AuthenticatedAiToolsIndexRoute,
  AuthenticatedAiToolsLiverFibrosisRoute:
    AuthenticatedAiToolsLiverFibrosisRoute,
  AuthenticatedAiToolsLiverPredictRoute: AuthenticatedAiToolsLiverPredictRoute,
  AuthenticatedAiToolsLiverSmcLudRoute: AuthenticatedAiToolsLiverSmcLudRoute,
  AuthenticatedAiToolsLiverSteatosisRoute:
    AuthenticatedAiToolsLiverSteatosisRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
